name: update scripts with file-sync
on:
  workflow_dispatch:
  schedule:
    # At 03:03 on Tuesday
    - cron: '3 3 * * 2'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: ./.github/sync.sh po5/thumbfast thumbfast.lua scripts/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update thumbfast"
      
      - run: ./.github/sync.sh mpv-player/mpv TOOLS/lua/autoload.lua scripts/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update autoload"

      - run: ./.github/sync.sh Hill-98/mpv-config scripts/auto-load-fonts.js
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update auto-load-fonts"

      - run: ./.github/sync.sh AN3223/dotfiles .config/mpv/scripts/pickshader.lua scripts/
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update pickshader"
      
      - run: |
          ./.github/sync.sh bloc97/Anime4K glsl/Upscale/Anime4K_Upscale_CNN_x2_L.glsl shaders/
          ./.github/sync.sh bloc97/Anime4K glsl/Upscale/Anime4K_Upscale_GAN_x2_M.glsl shaders/

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update Anime4K"

      # https://gist.github.com
      - run: |
          ./.github/sync.sh agyild/bbb4e58298b2f86aa24da3032a0d2ee6 '@gist' CAS-scaled.glsl shaders/
          ./.github/sync.sh agyild/82219c545228d70c5604f865ce0b0ce5 '@gist' FSR.glsl shaders/
          ./.github/sync.sh agyild/7e8951915b2bf24526a9343d951db214 '@gist' NVScaler.glsl shaders/

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update AMD/NVIDIA shaders"

      - run: |
          ./.github/sync.sh igv/8a77e4eb8276753b54bb94c1c50c317e '@gist' adaptive-sharpen.glsl shaders/
          ./.github/sync.sh igv/a015fc885d5c22e6891820ad89555637 '@gist' KrigBilateral.glsl shaders/
          ./.github/sync.sh igv/36508af3ffc84410fe39761d6969be10 '@gist' SSimDownscaler.glsl shaders/
          ./.github/sync.sh igv/2364ffa6e81540f29cb7ab4c9bc05b6b '@gist' SSimSuperRes.glsl shaders/

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update igv shaders"
      
      - run: |
          ./.github/sync.sh AN3223/dotfiles .config/mpv/shaders/nlmeans.glsl shaders/

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update nlmeans shaders"
      
      - run: |
          ./.github/sync.sh bjin/mpv-prescalers gather/nnedi3-nns128-win8x4.hook shaders/
          ./.github/sync.sh bjin/mpv-prescalers gather/ravu-zoom-ar-r3.hook shaders/

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update luma upscalers: nnedi3 and ravu"
      
      - run: |
          ./.github/sync.sh Artoriuz/glsl-chroma-from-luma-prediction CfL_Prediction.glsl shaders/

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update GLSL Chroma from Luma (CfL) Prediction"
