name: update scripts with file-sync
on:
  workflow_dispatch:
  schedule:
    # At 03:03 on Tuesday
    - cron: '3 3 * * 2'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: ./scripts/sync.sh po5/thumbfast thumbfast.lua scripts/thumbfast.lua
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update thumbfast"

      - run: ./scripts/sync.sh Hill-98/mpv-config scripts/auto-load-fonts.js
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update auto-load-fonts"
