name: update scripts with release-downloader
on:
  workflow_dispatch:
  schedule:
    # At 03:03 on Thursday
    - cron: '3 3 * * 4'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # sync uosc
      - uses: robinraju/release-downloader@v1.8
        with: 
          repository: "tomasklaen/uosc"
          latest: true
          extract: true
          fileName: "uosc.zip"
          out-file-path: "uosc"

      - run: |
          rm -rf scripts/uosc
          mv uosc/scripts/uosc scripts/
          mv uosc/fonts/* fonts/
          rm -rf uosc

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update uosc"

      # sync FSRCNNX
      - run: rm -f shaders/FSRCNN*.glsl
      - uses: robinraju/release-downloader@v1.8
        with: 
          repository: "igv/FSRCNN-TensorFlow"
          latest: true
          fileName: "*.glsl"
          out-file-path: "shaders"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update the FSRCNN-TensorFlow"
