name: Sync Files
on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '20 */4 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # sync uosc
      - uses: robinraju/release-downloader@v1.8
        with: 
          repository: "tomasklaen/uosc"
          latest: true
          extract: true
          fileName: "uosc.zip"
          out-file-path: "scripts"

      - uses: fregante/setup-git-user@v2
      - run: |
          rm scripts/uosc.zip
          git add scripts
          git commit -m "update uosc"

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}

      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
